### ISSUE TITLE
Create groups in my code?

### ISSUE THREAD

**Issue by endigma** [dave/jennifer#105]
Most of the examples function on a receiver pattern, like

```go
// g == some group

doSomething(g, params)
```

which affects `g` as a side effect. I prefer to write code in a more functional manner, is returning my own group to be used with `g.Add(...)` possible? I know I can just `g := new(Group)` but it means I have to manually add line breaks as the separator can't be set (private field).

**Comment by endigma** [comment]
If `Group` is meant for internal use only, perhaps another type for creating snippets functionally?

**Comment by dave** [comment]
Sorry I don't understand

**Comment by endigma** [comment]
I'd like to make a function like, say:

```go
func generateType(typespec *spec.Type) jen.Code {
    ...
}
```

that produces some `g.Add(...)`-able code to allow me to compose different functions to generate a more complex file.

currently, I'm doing it like this:

```go
func generateType(typespec *spec.Type) jen.Code {
    g := new(jen.Group)
	g.Commentf("foo").Line()
	return g
}
```

but `new(jen.Group)` doesn't have newlines, so I have to add them manually.

I found `jen.CustomFunc`, and it seems to work for what I want, but I'm not sure if it's the right way to do it.

Does that make sense?

**Comment by endigma** [comment]
Perhaps we could get a method like `CustomGroup(options) *Group` that uses the `Options` from `Custom`/`CustomFunc`?

```go
func CustomGroup(options Options) *Group {
	return &Group{
		close:     options.Close,
		multi:     options.Multi,
		name:      "custom",
		open:      options.Open,
		separator: options.Separator,
	}
}
```

**Comment by dave** [comment]
Can't you just do this?

```go
func generateType(typespec *spec.Type) jen.Code {
    c := jen.Commentf("foo").Line()
    return c
}
```

**Comment by endigma** [comment]
Yes, but my actual generators are a lot larger than that and consist of tens of different structures

**Comment by dave** [comment]
How about returning a `[]jen.Code`?

**Comment by endigma** [comment]
I used to use `[]jen.Code`, but then I had to write a bunch of logic for handling newlines etc. Perhaps a new construct for this usage would be best then?

Similar to `*Group` in that it has helpers for `append(g, ...)`, but with only basic options like `separator` to join all the items with `jen.Line()`.

**Comment by endigma** [comment]
Or just implying it's multiline, sort of like a file.

**Comment by dave** [comment]
How about:

```
	code := []jen.Code{...}
	for _, c := range code {
		g.Add(c)
	}
```

**Comment by endigma** [comment]
Yep, that works, there's still no append helpers for `[]jen.Code` though, and all the extra code does start to add up. I don't see why there shouldn't be a simpler way to achieve this pattern, using `[]jen.Code` with a workaround here and a workaround there doesn't make so much sense if the library could include all of the boilerplate.

I'm sure I'm not the only one who will ever want to build code like this, so a type like `Builder` or something that wraps all of this would be good.

**Comment by dave** [comment]
Where are you getting `g` from in that code?

**Comment by endigma** [comment]
it's a `&Group`, I'd have to repeatedly do the same pattern which is the "all the extra code does start to add up" I mentioned.

**Comment by dave** [comment]
This example test passes:

```go
func ExampleFoo() {
	block := BlockFunc(func(group *Group) {
		code := []Code{Comment("1"), Comment("2"), Comment("3")}
		for _, c := range code {
			group.Add(c)
		}
	})
	fmt.Printf("%#v", block)
	// Output:
	// {
	//	// 1
	//	// 2
	//	// 3
	// }
}
```

**Comment by endigma** [comment]
`CustomFunc` does it, but it puts the `Group` it makes into a closure instead of returning it.

**Comment by dave** [comment]
Yeah the solution is to use []Code, and only add to a Group when it's actually being added to code. 

(BTW I'm not going to add anything to Jennifer unless there's a bug to fix... the API is far too cluttered already to add more convenience methods)
