### ISSUE TITLE
example with multiple return types

### ISSUE THREAD

**Issue by technicallyty** [dave/jennifer#107]
was generating code that has multiple return types, but wasn't able to find a way to write that cleanly. currently what i'm doing is (and im not proud of this):

```go
		g.file.Func().Id("Unmarshal" + g.abiTypeStructName(obj.name)).
			Params(jen.Id("bz").List().Byte()).
			Id("(").
			Id(obj.name + ",").
			Id("error").
			Id(")").
			Block()
```

any help appreciated 🤟🏻

**Comment by dave** [comment]
What is the code you're trying to return?

**Comment by technicallyty** [comment]
```go
func Foo(bz []byte) (SomeStruct, error)
```

**Comment by dave** [comment]
Use https://github.com/dave/jennifer#params for that:

```go
`g.file.Func().Id("Unmarshal" + g.abiTypeStructName(obj.name)).
			Params(jen.Id("bz").List().Byte()).
			Params(jen.Id(obj.name), jen.Id("error")).
			Block()
```

**Comment by dave** [comment]
lol just realised who I'm talking to 😂 hey Tyler!

**Comment by technicallyty** [comment]
ah idk why i didnt think to just use params again lol. Thanks Dave! 

hahah hello! hope you've been enjoying your travels 🤝
