### ISSUE TITLE
Support `Array` for `Value` besides `Dict`?

### ISSUE THREAD

**Issue by suchen-sci** [dave/jennifer#109]
Hi, team:

In `Values`, when use `Dict`, the final order of output is random, since golang map is an unordered map. So could we support an `Array` for `Values` for keep the order in output?

**Comment by dnwe** [comment]
@suchen-sci I don't think the order is random, it's purposefully sort by key for repeatability https://github.com/dave/jennifer/blob/e319413f9534a6433810edb63d0e89bf2f88c555/jen/dict.go#L41

**Comment by dave** [comment]
Yes it's critical that subsequent runs produce identical source, so keys are sorted.
