### ISSUE TITLE
Feature: Should add a abstruct layer to make more Declarative?

### ISSUE THREAD

**Issue by chenyunda218** [dave/jennifer#114]
So far so good. But we have to carefully manual create `Struct`, `Method`, `Function`. So i think we should create a abstruct layer to create some complex code. And that can automatically assemble `jen`. In fact, I have already created a demo in my repo openapi-go-generator -> https://github.com/universalmacro/openapi-go-generator/tree/main/gen.
## Example
```go
type GStruct struct {
	Id      string
	Fields  []Field
	Methods []Method
}

func (gs GStruct) Statement() *jen.Statement {
	s := jen.Type().Id(gs.Id)
	fields := make([]jen.Code, len(gs.Fields))
	for _, f := range gs.Fields {
		fields = append(fields, f.Code())
	}
	s.Struct(fields...)
	return s
}
```

**Comment by dave** [comment]
This isn't something I want to add to this package. The namespace is already super cluttered as it is, and the idea is there's a close mapping between `jen` code and the generated code.

**Comment by dave** [comment]
In fact, [this](https://github.com/universalmacro/openapi-go-generator/blob/main/gen/gen_test.go) is exactly the sort of code that `jennifer` tries to avoid as much as possible...

**Comment by chenyunda218** [comment]
Thanks for your reply. I understand your intention, I will implement this abstraction layer on my another repository. Avoid cluttered code as much as possible.
