### ISSUE TITLE
Multi-line formatting for long parameter lists

### ISSUE THREAD

**Issue by mickeyreiss** [dave/jennifer#17]
Is there currently a way to trigger multi-line formatting for long parameter lists? If not, is this something that would be useful to contribute to the library? I find multi-line parameter lists easier to read and create more useful diffs.

***

Here's a contrived example to demonstrate.

Currently:

```go
package main

import (
	"os"

	"github.com/dave/jennifer/jen"
)

func main() {
	f := jen.NewFile("test")

	f.Func().Id("PrintNumbers").Call().Block(
		jen.Qual("fmt", "Println").ParamsFunc(func(g *jen.Group) {
			for idx := 0; idx < 10; idx += 1 {
				g.Lit(idx)
			}
		}),
	)

	if err := f.Render(os.Stdout); err != nil {
		panic(err)
	}
}
```

Outputs:

```go
package test

import fmt "fmt"

func PrintNumbers() {
	fmt.Println(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
}
```

Desired:

```go
package test

import fmt "fmt"

func PrintNumbers() {
	fmt.Println(
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
	)
}
```

**Comment by dave** [comment]
Hmm I'm not sure I want to complicate the API with control over the formatting of the output...

**Comment by mickeyreiss** [comment]
Agreed. I like the directness of the API as it is today. 

What if the formatting were based on a simple heuristic. For example, use multi-line formatting if the parameter count is greater than 3.

**Comment by dave** [comment]
How about:

```go
package main

import (
	"os"

	"github.com/dave/jennifer/jen"
)

func main() {
	f := jen.NewFile("test")

	f.Func().Id("PrintNumbers").Call().Block(
		jen.Qual("fmt", "Println").ParamsFunc(func(g *jen.Group) {
			for idx := 0; idx < 10; idx += 1 {
				g.Line().Lit(idx)
			}
		}),
	)

	if err := f.Render(os.Stdout); err != nil {
		panic(err)
	}
}
```

Output:
```go
package test

import fmt "fmt"

func PrintNumbers() {
	fmt.Println(
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9)
}
```

**Comment by dave** [comment]
That's a bit of a kludge 😉

**Comment by mickeyreiss** [comment]
Not perfect (final parameter on same line as `)`), but it'll work for me for now! Thanks for the quick support, @dave!  :octocat: :tada:

**Comment by mickeyreiss** [comment]
Also, if you change your mind about it, I'd be happy to take a try at contributing the change.

**Comment by dave** [comment]
I'll have a think... but trying to support everyone's version of exactly how they want the output to be formatted will open a rather large can of worms, so I wouldn't hold your breath!

**Comment by dave** [comment]
But thanks for the input - it's really useful to see how people are using it!
