### ISSUE TITLE
IF statement with multiple conditions (using && and ||)

### ISSUE THREAD

**Issue by surfeurX** [dave/jennifer#19]
Thank you for the amazing package.

I was wondering if it's possible to create an IF statement with multiple conditions ?

**Comment by dave** [comment]
Hey, thanks for trying my package!

It's definitely possible to do that... `&&` would be `Op("&&")`, and `||` would be `Op("||")`. If you need some parenthesis to make the execution order clear, you can use `Params(...)`.

```go
c := If(Params(Id("a").Op("||").Id("b")).Op("&&").Id("c")).Block()
fmt.Printf("%#v", c)
// Output:
// if (a || b) && c {
// }
```

I've added this as another example in the [Operators section](https://github.com/dave/jennifer#operators) of the readme. Don't hesitate to get back to me if you need any more help... I'm happy to review any code you write - just add @dave in your PR comment and I'll take a look!

**Comment by surfeurX** [comment]
That's exactly what I was looking for. Thank you so much I just avoided hours debugging the go/ast package  :)
