### ISSUE TITLE
Adding imports manually

### ISSUE THREAD

**Issue by kujtimiihoxha** [dave/jennifer#20]
Is there a way to add imports manually just like `jen.Anon` without using  `jen.Qual`. I have a case where I can not use `jen.Qual` but I need to specify some imports.

**Great project btw.**

**Comment by dave** [comment]
Thanks! Can you explain the case where you need to add a non-anonymous import without using `Qual`?

**Comment by kujtimiihoxha** [comment]
Hey Dave, thanks for your response, I am rewriting https://github.com/kujtimiihoxha/gk and I am using jennifer instead of using go templates.

I do not know how familiar you are with `go-kit` but nevertheless, this is my issue
So the problem is this:

I am creating a generator that is using an interface as a basis for generating boilerplate code.

Let's say I have this source:

```
package service

import (
	"context"

	"github.com/kujtimiihoxha/gk-cli/test_dir/hi/pkg/io"
)

// HIService describes the service.
type HIService interface {
	Foo(ctx context.Context, test io.Test) (err error)
	Bar(ctx context.Context, b []map[string]string) (err error)
}
```

Now I have my own logic that reads the file and I get all the functions of the service interface and its parameters/results 

Next, I am generating a file that looks like this:

```
package service

import (
	"context"

	log "github.com/go-kit/kit/log"
	"github.com/kujtimiihoxha/gk-cli/test_dir/hi/pkg/io"
)

// Middleware describes a service middleware
type Middleware func(HIService) HIService

type loggingMiddleware struct {
	logger log.Logger
	next   HIService
}

// LoggingMiddleware takes a logger as a dependency
// and returns a HIServiceMiddleware.

func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next HIService) HIService {
		return &loggingMiddleware{logger, next}
	}
}
func (mw loggingMiddleware) Foo(ctx context.Context, test io.Test) (err error) {
	defer func() {
		mw.logger.Log("method", "Foo", "ctx", ctx, "test", test, "err", err)
	}()
	return mw.next.Foo(ctx, test)
}

func (mw loggingMiddleware) Bar(ctx context.Context, b []map[string]string) (err error) {
	defer func() {
		mw.logger.Log("method", "Bar", "ctx", ctx, "b", b, "err", err)
	}()
	return mw.next.Bar(ctx, b)
}

```

And I know that this file will have the same imports (+ some additions) that the service file has but the issue is with `test io.Test` the function's parameters and results can be any kind of type and I do not always know what the import path of them is.

So my idea was just to grab the imports of the service (which are already there and my code picks them up) and import them into the other file, this would guaranty that I have my necessary imports in the generated file.

I do not know if my example is clear but thanks for your help.

**Comment by dave** [comment]
Am I correct in saying that this problem is more clear when the file you're scanning looks like this?

```go
package service

import (
	"github.com/badly_named_package_1" // <- this is foo
	"github.com/badly_named_package_2" // <- this is bar
)

type X interface {
	Y(f foo.Foo, b bar.Bar) ()
}
```

... when you're scanning the file with AST you have no way of telling which of the imports correspond to `foo` and `bar`.

However, is it a possibility to scan the file with [go/types](https://golang.org/pkg/go/types/)? That would allow you to resolve the package of each expression. There's loads of [good documentation here](https://github.com/golang/example/tree/master/gotypes).

Let me know if I've misunderstood...

**Comment by kujtimiihoxha** [comment]
>... when you're scanning the file with AST you have no way of telling which of the imports correspond to foo and bar.

This is exactly my issue, I have no prior experience with `go.types` but I tried the simple example that is shown in their repo but looks like I am doing something wrong.

```
package main

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
)
const svc = `package service

import (
	"context"

	io "github.com/kujtimiihoxha/gk-cli/test_dir/ciao/pkg/io"
)

// CiaoService describes the service.
type CiaoService interface {
	// Add your methods here
	Foo(ctx context.Context, test io.Test) (err error)
	Bar(ctx context.Context, b []map[string]string) (err error)
}

type basicCiaoService struct{}

func (c *basicCiaoService) Foo(ctx context.Context, test io.Test) (err error) {
	// TODO implement the business logic of Foo
	return err
}
func (c *basicCiaoService) Bar(ctx context.Context, b []map[string]string) (err error) {
	// TODO implement the business logic of Bar
	return err
}

// New returns a basic CiaoService with all of the expected ≈ wired in.
func New(middleware []Middleware) CiaoService {
	var svc CiaoService = NewBasicCiaoService()
	for _, m := range middleware {
		svc = m(svc)
	}
	return svc
}

// NewBasicService returns a naive, stateless implementation of CiaoService.
func NewBasicCiaoService() CiaoService {
	return &basicCiaoService{}
}
`

func main(){
	fset := token.NewFileSet()


	f, err := parser.ParseFile(fset, "svc.go", svc, 0)
	if err != nil {
		log.Fatal(err) // parse error
	}

	// A Config controls various options of the type checker.
	// The defaults work fine except for one setting:
	// we must specify how to deal with imports.
	conf := types.Config{Importer: importer.Default()}

	// Type-check the package containing only file f.
	// Check returns a *types.Package.
	pkg, err := conf.Check("ciao/pkg/service", fset, []*ast.File{f}, nil)
	if err != nil {
		log.Fatal(err) // type error
	}

	fmt.Printf("Package  %q\n", pkg.Path())
	fmt.Printf("Name:    %s\n", pkg.Name())
	fmt.Printf("Imports: %s\n", pkg.Imports())
	fmt.Printf("Scope:   %s\n", pkg.Scope())
}

```

But when I run it I I am getting this : 
```
2017/09/15 13:15:30 svc.go:6:5: could not import github.com/kujtimiihoxha/gk-cli/test_dir/ciao/pkg/io (can't find import: "github.com/kujtimiihoxha/gk-cli/test_dir/ciao/pkg/io")
exit status 1
```
Thanks a lot for your help.

**Comment by dave** [comment]
I'd recommend using the `golang.org/x/tools/go/loader` package to scan the file... Take a look at how I've used it in my [courtney project](https://github.com/dave/courtney/blob/master/scanner/scanner.go)...

**Comment by kujtimiihoxha** [comment]
@dave thanks for your suggestions, I think for what I am trying to do this is complicating things a bit too much but I am using `imports.Process` after the generated code from jennifer and it is adding missing imports (well.. if there are not multiple imports that match). 

Either way, I think to add a function like `jen.Import(jen.Id("io").jen.Lit("my/path"))` is not a big deal looking at `jen.Anon`. I bet you have a reason why you did not expose this kind of API. Let me know if you want me to submit a PR that would allow this behavior.

Thanks again for your effort.

**Comment by kujtimiihoxha** [comment]
Actually I think I found a solution.
Lets say I have something like `io.Test` I know that  the import path of that library must end with `io` or it must be something like `io "some/path" so I just search for that import path and use it with `Qual` this solves my issue.

**Comment by dave** [comment]
Yes I'd like to keep the API as simple as possible, so having more control over the import block isn't something I would consider without a really significant use case. 

The fact that `Qual` automatically adds imports is important, and adding an additional `Import` would no doubt confuse beginners.

It seems this is a really specific corner case. I'm not sure complicating the API to make it possible would benefit the community overall...

**Comment by dave** [comment]
... remember that the name of the package doesn't have to be in the import path. It's good practise to have it there, but occasionally packages (e.g. my `badly_named_package_1` example) will not use best practise. If in your case you can guarantee that, then you're good to go.

**Comment by kujtimiihoxha** [comment]
Ok thanks a lot for your help @dave I am closing this issue as this is not relevant anymore.

**Comment by kujtimiihoxha** [comment]
Yeah I will add some notes for this cases in the generator docs so users should use `io "any/package"` style of importing parameters and results... Pretty hard to create a general purpose generator without being somewhat opinionated

Thanks

**Comment by andreykaipov** [comment]
This is an old issue, but here's my use-case and a workaround below for anybody else that stumbles across this issue.

I have a `map[string]string` of field names to type names, e.g.

```
"name" -> "string"
"date" -> "time.Time"
"abc" -> "map[time.Time]string"
```

Which I found from parsing the objects from my `*ast.File` and resolving the types of each field.

Extracting the qualified identifiers out of something like `map[time.Time]string` seems annoying and I'd rather just surround the entire value in an `Id()` and be done with it. Sure I could modify my parsing algorithm to identify potential qualified identifiers out of the `*ast.SelectExpr` expressions I find, but I think it'd really complicate things.

Just like @kujtimiihoxha, my generator's imports will be the same as the file it was generated from, so I figure it's just easier to add them in directly. And that's what I've done:

```
imports := Empty()
for _, p := range pkg.Imports {
	imports.Add(Id(p.Name).Lit(p.PkgPath), Line())
}

f := NewFile(pkg.Name)
f.Add(Id("import").Parens(imports))
```

Here `pkg` is a [`go/packages#Package`](https://godoc.org/golang.org/x/tools/go/packages#Package).

**Comment by jbonzo** [comment]
Let me know if I should make a new issue for this, but I think there could be a valid use case for allowing manual imports when it comes to package linking.

I am trying to generate code that uses the new [`embed`](https://golang.org/pkg/embed/) directive and it requires doing an import such as 
```golang
import _ "embed"

//go:embed hello.txt
var s string
print(s)
```

Currently I don't have a way to accomplish this using jennifer.

**Comment by dave** [comment]
Check out file.Anon for the anonymous import case...
