### ISSUE TITLE
Object literal incorrectly qualified when using Lit()

### ISSUE THREAD

**Issue by joshdk** [dave/jennifer#24]
BLUF - Object literals will be qualified with a package name, even when rendered into a fully-qualified, identical package.

Let me illustrate with an example. Say I have a package called `github.com/joshdk/example`, [which contains these two Go files](https://gist.github.com/joshdk/7fb2ff57967a22e801803bf40842b3bc).

When I run the `TestRender` function, I **expect** to see the following code printed out:

```go
package example

var author = Person{Name: "Linus"}
```

But instead, what **actually** gets generated is this:

```go
package example

var author = example.Person{Name: "Linus"}
```

Which would eventually result in an error if I wrote this contents to a file inside of the `github.com/joshdk/example` package. It would be helpful if a literal (via `Lit()`) compared its type against the declared package (and simplified if they matched) at render time.

Fantastic project by the way. Cheers!

**Comment by joshdk** [comment]
The workaround is to use something like the following, which requires repeating the type and each struct field:

```go
f.Var().Id("author").Op("=").Qual("github.com/joshdk/example", "Person").Values(jen.Dict{
	jen.Id("Name"): jen.Lit(linus.Name),
})
```

**Comment by dave** [comment]
> Fantastic project by the way. Cheers!

Thanks!

OK so I've never anticipated `Lit` to be used with anything but simple values. Your workaround is how I designed it to be used.

You can see the render code here:

https://github.com/dave/jennifer/blob/master/jen/tokens.go#L41-L64

Anything that isn't a basic type is simply rendered with the `%#v` verb from `fmt`... which will fail for anything that includes a qualified name. 

Extending `Lit` to support printing Go code for arbitrary objects will be a complex undertaking (and there's plenty of objects that can't be expressed in a literal).
