### ISSUE TITLE
Using a defined type.

### ISSUE THREAD

**Issue by pekim** [dave/jennifer#27]
I can see how to define a type.

```go
c := jen.Type().Id("mytype").Int32()
fmt.Printf("%#v\n", c)
```
That will produce this.
```go
type mytype int32
```

But I can't figure out how to later define a var of that type.
```go
var a mytype
```

**Comment by pekim** [comment]
To expand further, I'm currently trying to generate something like this.
- define a type
- some const defs, each of which
  - is of the defined type
  - is preceded by some comment lines

```go
type mytype C.some_type

const (
	// doc comment for enumA
	enumA mytype = C.some_value_a

	// doc comment for enumB
	enumB mytype = C.some_value_b

	// doc comment for enumC
	enumC mytype = C.some_value_c
)
```
And I struggling to work out how to use the api to achieve this.

**Comment by pekim** [comment]
Ah, using `Const().DefsFunc(...)` gives me the flexibility to generate the comment and def for each item.

So I'm back to my original issue of how to use a defined type.

**Comment by dave** [comment]
`var a mytype` would be simply `jen.Var().Id("a").Id("mytype")`

**Comment by dave** [comment]
... and yes, you're on the right track with `Const().DefsFunc(...)`

**Comment by pekim** [comment]
I could have sworn that I'd tried the `jen.Var().Id("a").Id("mytype")` approach. But obviously I hadn't as it works just fine.

Thanks for your help. I think that I'm getting a feel for the api now.
