### ISSUE TITLE
Feature proposal: Qual from reflect.Type

### ISSUE THREAD

**Issue by jawnsy** [dave/jennifer#29]
Hi there!

Thanks for this fantastic library, I've been playing with it for a few days now, and it's been great. I'd just like to make a small suggestion (and am happy to submit a pull request) which would make things easier for my particular use case.

I'm using reflection to generate ORM-ish code at compile time. For example, for a given struct, I want to use reflection to determine type information, and then pass it to jennifer. Currently, this means writing code like:

```go
t := reflect.TypeOf(api.Account{}),
account := jen.Qual(t.PkgPath(), t.Name())
```

It would be nice if there was a convenience function for this:

```go
func QualType(t reflect.Type) *Statement {
	return newStatement().Qual(t.PkgPath(), t.Name())
}
```

This is a small thing and has the downside of cluttering the jennifer API a bit. However, it shouldn't have any new dependencies, since jennifer already needs `fmt` which depends on `reflect`. I'd be happy to implement this and submit a pull request, but would need some guidance.

Thanks for your consideration!

**Comment by dave** [comment]
Thanks for the suggestion... I think I'll pass on this one... It's pretty trivial to do `jen.Qual(t.PkgPath(), t.Name())`, and as you know the API really doesn't need to get any more cluttered. 

Let me know if you have any more suggestions!
