### ISSUE TITLE
Feature request: Method chaining with PackageComment/HeaderComment

### ISSUE THREAD

**Issue by jawnsy** [dave/jennifer#35]
Hi Dave,

I didn't see any discussion in #23 about this, though I understand these methods are different from most of `jen`'s methods, since they are on `File` rather than `Statement`.

Currently, we can do something like:

```go
	f.Comment("Hello").Line().
		Comment("World").Line()
```

and this would be rendered as:

```
// Hello
// World
```

However, this isn't possible with PackageComment or HeaderComment, since they don't return anything. If they at least returned `*File`, then they could be used to chain subsequent calls, e.g.

```go
	f.PackageComment("Hello").
		PackageComment("World")
```

Additionally, neither of these support the `fmt.Sprintf` variant, à la `stmt.Commentf`. Do these seem like worthwhile enhancements to make? Or is there some reason why `File` cannot currently support a pattern like this?

Thanks for everything, you're awesome! 🎉 

Best,

Jonathan

**Comment by dave** [comment]
I'm not super keen on this. `PackageComment` and `HeaderComment` are typically used only once and very rarely need anything special chained after them. Your example of two line comments can be accomplished by either:

1) [making several calls to the comment method](https://play.jsgo.io/76e9ec4f17479bfa04b116f94ef7519447ec1c34)
2) [passing your entire comment to the method](https://play.jsgo.io/c768697eab791b849449c22b71b79385d264b610) - if the comment prefix (`//` or `/*`) is included, the string is emitted unchanged including any formatting.

**Comment by jawnsy** [comment]
Maybe a change to make them variadic would work better?

```
f.PackageComment(
	"Hello",
	"World",
)
```

I think this looks cleaner than using `\n` and manually adding the `//` prefix.

Maybe an alternative is to use `github.com/renstrom/dedent` and a multi-line string literal like so: https://play.jsgo.io/77dde4cfc6bb898663100156bb43c4bf1c5d0405

**Comment by dave** [comment]
Thanks for the suggestions, but I'm pretty happy with how it works now... package comments are relatively uncommon so I don't think we need to complicate the API. I'm going to close this, but get back in touch if you have any more ideas.
