### ISSUE TITLE
missing ',' before newline in composite literal

### ISSUE THREAD

**Issue by magicsong** [dave/jennifer#49]
When i use following codes
```go
Block(gen.Id("client").Op(":").Id("c"))
```
it render as 
```
& ComponentsService {
client : c
}
```

Is it a bug？Should add a "," after `c`

**Comment by dave** [comment]
For map or composite literals, use [Values and Dict](https://github.com/dave/jennifer#values):

```go
c := Op("&").Id("Person").Values(Dict{
	Id("Age"):	Lit(1),
	Id("Name"):	Lit("a"),
})
fmt.Printf("%#v", c)
// Output:
// &Person{
// 	Age:  1,
// 	Name: "a",
// }
```

**Comment by dave** [comment]
You can also use DictFunc:

```go
c := Id("a").Op(":=").Map(String()).String().Values(DictFunc(func(d Dict) {
	d[Lit("a")] = Lit("b")
	d[Lit("c")] = Lit("d")
}))
fmt.Printf("%#v", c)
// Output:
// a := map[string]string{
// 	"a": "b",
// 	"c": "d",
// }
```

**Comment by magicsong** [comment]
Thanks for your lightning-fast reply! /close

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dave** [comment]
No problem. Let me know if you get stuck again - happy to help!

**Comment by dave** [comment]
Yes I've noticed this before but at the time couldn't find an elegant solution. I'll create a new issue to track this bug.

**Comment by dave** [comment]
https://github.com/dave/jennifer/issues/51
