### ISSUE TITLE
Custom package names

### ISSUE THREAD

**Issue by purrcat259** [dave/jennifer#53]
Hi there,

Thank you for this package, it has really reduced the time I thought I would need to get into codegen.

Wanted to ask a question about whether custom package names are possible.
In my case, I am generating repository functions in a structure similar to the following:
mypkg/
|--> create.go
|--> read.go
|--> update.go
|--> destroy.go

In my code I am using: `f := NewFile("create")` which when saving, sets package to `package create`. I would however instead like to be able to set `package mypkg`, so that I can generate a whole package (in my example, `mypkg`).

Thank you for your time!

**Comment by dave** [comment]
How about `f := NewFile("mypkg")`?

**Comment by dave** [comment]
(The parameter you're passing to the `NewFile` function isn't the filename, it's the package name. The filename is only specified when you save the file).

**Comment by purrcat259** [comment]
Ah, you're 100% correct. I even save the files with different filenames but completely missed this detail. Thank you!

**Comment by dave** [comment]
Awesome. Glad it's useful for you!
