### ISSUE TITLE
[Feature request] `Idf` func

### ISSUE THREAD

**Issue by mickeyreiss** [dave/jennifer#62]
I find myself writing `jen.Id(fmt.Sprintf("%sThing", model))` relatively often.

It would be convenient to add a helper method for this pattern, `Idf`.

**Comment by dave** [comment]
Hmm this might be useful but I’m rather hesitant to include any more functions to the already crowded namespace...

**Comment by mickeyreiss** [comment]
Okay, there’s an easy workaround, so it’s not a big deal. 

If others agree with my proposal, I’d be happy to submit a PR in the future.
