### ISSUE TITLE
If multiply conditions

### ISSUE THREAD

**Issue by utya1988** [dave/jennifer#68]
Hello. Thanks for your library. Im  new in golang.
Could you help me.

I want generate multiply conditions for "if" in for cycle. But have problems.
Now im trying 

var ifstringCode []Code
condition1 := Id("a").Op(params).Id(value)
condition1 := Id("a").Op(params).Id(value1)
ifstringCode =append(ifstringCode,If(Parens(condition1)))

and want add another conditions.

Some like this.

if (a>1)&&(b==1)
if (a>1)&&(b==1)&&(c==1)

**Comment by dave** [comment]
For variable numbers of conditions, best to use the `Do` function, like this:

```go
func TestVariableConditions(t *testing.T) {
	conditions := []Code{
		Id("a").Op("<").Lit(1),
		Id("b").Op(">").Lit(2),
		Id("c").Op("==").Lit(3),
	}

	c := If(Parens(conditions[0]).Do(func(s *Statement) {
		for i := 1; i < len(conditions); i++ {
			s.Op("&&").Parens(conditions[i])
		}
	})).Block()
	
	fmt.Printf("%#v", c)
}
```

output:

```go
if (a < 1) && (b > 2) && (c == 3) {
}
```

Does that make sense?

**Comment by utya1988** [comment]
Thanks.
