### ISSUE TITLE
How generate a field of time.Time type in a struct?

### ISSUE THREAD

**Issue by leopku** [dave/jennifer#70]
Thanks for this awesome project.

I'm troubled to generate time.Time field of struct.

Hopeful go code is:
```
type MyStruct struct {
  Name string
  Birthday time.Time
}
```

How to write jennifer code?
```
Type().Id("MyStruct").Struct(
  Id("Name").String(),
  Id("Birthday").???    //   <-- How to write?
)
```

**Comment by dave** [comment]
Simple! `time.Time` is an identifier from another package, so you use `Qual` (Qualified Identifier). [Here's the docs](https://github.com/dave/jennifer#qual).

```go
Type().Id("MyStruct").Struct(
  Id("Name").String(),
  Id("Birthday").Qual("time", "Time"),
)
```

**Comment by dave** [comment]
... this will also automagically add the "time" insert to the imports block.

**Comment by leopku** [comment]
> Here's the docs

awesome.
Big thanks.
