### ISSUE TITLE
Feature Rquest: a better alias guess function

### ISSUE THREAD

**Issue by zoumo** [dave/jennifer#72]
If the import alias is invalid or has been registered already, jennifer make it unique by appending a number. This led to an ugly generated code with imports block, for example
```
package test

import (
	v1 "k8s.io/core/v1"
    v11 "k8s.io/apps/v1"
    v12 "k8s.io/batch/v1"
    v13 "k8s.io/xxx/v1"
)
```

A better output is 
```
package test

import (
	v1 "k8s.io/core/v1"
    appsv1 "k8s.io/apps/v1"
    batchv1 "k8s.io/batch/v1"
    xxxv1 "k8s.io/xxx/v1"
)
```

**Comment by zoumo** [comment]
There are two way to achieve this goal
1. change the default behavior when alias is invalid in `File.register(path string) string`
```
	// If the name is invalid or has been registered already, calculate an import alias by joining
	// path parts utill we get something unique not just appending a number
	unique := name
	restPath := path
	for !f.isValidAlias(unique) {
		// otherwise, calculate an import alias by joining path parts till we get something unique
		restPath, _ = gopath.Split(restPath)
		if restPath == "" {
			unique += "x"
		} else {
			nextWord := guessAlias(restPath)
			unique = nextWord + unique
			restPath = restPath[:len(restPath)-1]
		}
	}
```

**Comment by zoumo** [comment]
@dave

**Comment by dave** [comment]
I think remaining backwards compatible is really important, so the first idea is not ideal. I'm also unconvinced that we gain enough from the second idea to warrant further complication of the API. The problem with making the alias guessing function more intelligent is that you soon run into edge cases where any clever algorithm falls down.

Although not a catch-all, you can use [File.InputAlias](https://github.com/dave/jennifer#importalias), [File.InputName](https://github.com/dave/jennifer#importname) or the [gennames](https://github.com/dave/jennifer/tree/master/gennames) tool to supply hints for alias / package names...
