### ISSUE TITLE
Question: is it possible to open an existing file and modify an existing function to add code to it?

### ISSUE THREAD

**Issue by eljuanchosf** [dave/jennifer#74]
Say that I have this:
```go
func doThings() {
    doOneThing()
}
```
and I want to add, at the end, the `doAnotherThing()` function so it will read:
```go
func doThings() {
    doOneThing()
    doAnotherThing()
}
```

Is this possible? If not, would it be something useful to think about?

**Comment by dave** [comment]
No that's not what this package was designed for. However my other package [dst](https://github.com/dave/dst) does exactly this.

**Comment by eljuanchosf** [comment]
Thank you! I will check it out, and thanks for the quick response too! :)
