### ISSUE TITLE
[Help wanted]How to generate correct 'go:generate'?

### ISSUE THREAD

**Issue by leopku** [dave/jennifer#78]
AS `go:generate` was a special type of comments.
Codes generated by both
```go
f.HeaderComment("go:generate go version")
```
and
```go
f.Line().Comment("go:generate go version")
```
was
```go
// go:generate go version
```
which could not run by `go generate ./...`

What's the correct way to generate code like below?
```go
//go:generate go version
```

**Comment by dave** [comment]
Try:

'''go
f.HeaderComment("//go:generate go version")
'''

**Comment by dave** [comment]
See the last part of the comment documentation: https://github.com/dave/jennifer#comment

![image](https://user-images.githubusercontent.com/925351/111899117-656b8b00-8a22-11eb-835e-6ea7dde63101.jpeg)
