### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by inluxc** [dave/jennifer#79]
I have the following to import but it removes the "is" package
```
f.ImportName("github.com/go-ozzo/ozzo-validation/v4", "validation")
f.ImportAlias("github.com/go-ozzo/ozzo-validation/v4/is", "is")
```

**Comment by dave** [comment]
Can you post a complete example?

**Comment by inluxc** [comment]
Question to the import to work do we need to use Qual "Qual("fmt", "Errorf")"  ???

**Comment by dave** [comment]
The ImportName and ImportAlias methods you've poster above just inform Jennifer that you'd like to use that name or alias for the package. If you don't include that package in a Qual somewhere in your code, it won't be added to the import block...

**Comment by inluxc** [comment]
Thanks for the input, resolved. I did not have the Qual for the package.
Closing this issue.
