### ISSUE TITLE
Arbitrary Precision Constants

### ISSUE THREAD

**Issue by bemasher** [dave/jennifer#80]
I'm transforming generated code that uses numeric constants with unusually high precision. Rather than parse them as floats and render them with `jen.Lit`, is there a way to render the constant's value exactly as it is provided?

It looks like `jen.Id` passes its arguments through unchanged, so I'm currently using that. An example constant is as follows:

```
DK(KP866025403, +0.866025403784438646763723170752936183471402627);
```

And rendered using `jen.Id` for the value produces:
```go
const (
	KP866025403 = +0.866025403784438646763723170752936183471402627
)
```

By the way, jen is a joy to use.

**Comment by dave** [comment]
Yes you're right, `jen.Id` will be an acceptable hack for this. 

I've considered adding `jen.Raw` to emit raw text into the output stream, but I think this might encourage people to use `Raw` when more appropriate features are available.

**Comment by bemasher** [comment]
I agree about the potential for misuse of something like `jen.Raw`. I'll stick with `jen.Id` for this case. Thanks.
