### ISSUE TITLE
Tags of a struct should be comma separated

### ISSUE THREAD

**Issue by tecsavy97** [dave/jennifer#82]
While I was defining a struct, the tags method that is used doesn't make the tags comma separated, i.e `json:"" graphql:""`

**Comment by dave** [comment]
By convention struct tags are [separated by spaces, not commas](https://levelup.gitconnected.com/struct-field-tags-in-go-fcc2428a1f91#:~:text=value%22%20and%20are-,separated%20by%20space,-.%20That%20is%2C%20you)...
