### ISSUE TITLE
Looking for call chaining including line-feeds

### ISSUE THREAD

**Issue by mcrawfo2** [dave/jennifer#87]
I am trying to generate a multi-line call chain but go requires the newline between the Dot and the Id, such as:

```go
cfg := NewConfigBuilder().
       WithValue("k", "v").
       WithValue("a", "b").
       Build()
```

Currently `Dot` does not appear to support such a mechanism.  I've added a `DotLine` method to Statement (below) but was wondering if there was some canonical way to do this already.  If not, can a solution be added?

```go
// DotLine renders a period followed by an newline and an identifier. Use for call chaining.
func (s *Statement) DotLine(name string) *Statement {
	d := token{
		typ:     delimiterToken,
		content: ".\n",
	}
	t := token{
		typ:     identifierToken,
		content: name,
	}
	*s = append(*s, d, t)
	return s
}
```

**Comment by dave** [comment]
Aah unfortunately Jennifer is intentionally simplified... it's more concerned with outputting correct code rather than good looking code.

**Comment by thieman** [comment]
@dave could you clarify whether you're saying "I won't accept a PR that fixes this" or just "I won't do this myself"?

**Comment by dave** [comment]
I won't accept a PR that implements this

**Comment by thieman** [comment]
Thanks for clarifying! Should this issue be closed then?

**Comment by dave** [comment]
Sure feel free to close it.

**Comment by thieman** [comment]
Not my issue or I would 😂

**Comment by dave** [comment]
😂 sorry I'm half asleep today
