### ISSUE TITLE
Non-int untyped numeric literal

### ISSUE THREAD

**Issue by tv42** [dave/jennifer#95]
Go constants are larger than `int` ("Represent integer constants with at least 256 bits." https://go.dev/ref/spec#Constants). If you try to use `.Lit` with even `int64`, jennifer makes it a typed constant.

Maybe `.Lit` should support [math/big](https://pkg.go.dev/math/big), and just insert the stringification as literal value -- those non-builtin types can never be typed constants, so there's no other possible interpretation.

**Comment by tv42** [comment]
Maybe if the caller wants a conversion, the caller should ask for a conversion..

**Comment by dave** [comment]
I don't think this is a huge problem in real-world usage... Probably not big enough to further complicate the library. If you really need to emit a numeric const that overflows int, you could kludge it with `Id` - something like:

jen.Const().Id("BigNumber").Op("=").Id("100000000000000000000000")
