### ISSUE TITLE
How to generate complex type field definitions in Struct

### ISSUE THREAD

**Issue by WanXinTao** [dave/jennifer#96]
@dave How should I use Jennifer to generate the Date field and Image field
![image](https://user-images.githubusercontent.com/21972225/195104843-214c23a9-09bb-4282-919c-3764caf0fcf2.png)

Thanks～

**Comment by WanXinTao** [comment]
i know  use `Id("age").Op("*").Int64() ` generate age field
but the date field is not a basic type, so how should I generate this field definition?

**Comment by dave** [comment]
Check out the Tag method: https://github.com/dave/jennifer#tag

**Comment by WanXinTao** [comment]
> For the Date field, you'd use something like:
> 
> ```go
> Id("Date").Index().Op("*").Qual("time", "Time").Tag(map[string]string{"json": "date"})
> ```
Thanks, this is what I want
