### ISSUE TITLE
How to Gennerate var()?

### ISSUE THREAD

**Issue by hellertang** [dave/jennifer#99]
Hello, thanks for your library.
Could it generate go code like following ?
```
var (
    request  = organization.NewCreateXXXRequest()
    response *organization.CreateXXXXXResponse
    uin      int64
)
```

**Comment by dave** [comment]
Check out `Defs` in the `Parentheses` section of the readme...

**Comment by hellertang** [comment]
Thanks, Got it !
I find `Dict{}` will automatically sort the elements according to the first letter. Is there a way to disable this feature？

**Comment by dave** [comment]
No, unfortunately not. Jennifer is concerned with producing valid code. Simplicity of the api is preferable over exact control of the style of the output.
